// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $api_help from './routes/api/help.ts';
import * as $index from './routes/index.tsx';
import * as $info from './routes/info.tsx';
import * as $note_bash_post_PlayMinecraftUsingGPU from './routes/note/bash/post-PlayMinecraftUsingGPU.tsx';
import * as $note_bash_post_SetAutomaticExecutionBashScript from './routes/note/bash/post-SetAutomaticExecutionBashScript.tsx';
import * as $note_bash_post_Utility from './routes/note/bash/post-Utility.tsx';
import * as $profile from './routes/profile.tsx';
import * as $sample from './routes/sample.tsx';
import * as $template from './routes/template.tsx';
import * as $terms from './routes/terms.tsx';
import * as $Common_Code from './islands/Common/Code.tsx';
import * as $Original_Frame_Board from './islands/Original/Frame/Board.tsx';
import * as $Original_Frame_Frame from './islands/Original/Frame/Frame.tsx';
import * as $Original_Frame_FrameFunction from './islands/Original/Frame/FrameFunction.tsx';
import * as $Original_Frame_FrameObject from './islands/Original/Frame/FrameObject.tsx';
import * as $Original_Info_Info from './islands/Original/Info/Info.tsx';
import * as $Original_Info_InfoAdvance from './islands/Original/Info/InfoAdvance.tsx';
import * as $Original_Menu_Menu from './islands/Original/Menu/Menu.tsx';
import * as $Original_Miscellaneous_MultilingualContent from './islands/Original/Miscellaneous/MultilingualContent.tsx';
import * as $Original_Miscellaneous_MultilingualContentSwitcher from './islands/Original/Miscellaneous/MultilingualContentSwitcher.tsx';
import * as $Utility_Data_getLanguageCodeData from './islands/Utility/Data/getLanguageCodeData.tsx';
import * as $Utility_Info_getAllInfo from './islands/Utility/Info/getAllInfo.tsx';
import * as $Utility_Info_getDeviceInfo from './islands/Utility/Info/getDeviceInfo.tsx';
import * as $Utility_Info_getPlaceInfo from './islands/Utility/Info/getPlaceInfo.tsx';
import * as $Utility_Info_getTimeInfo from './islands/Utility/Info/getTimeInfo.tsx';
import * as $Utility_alignDigit from './islands/Utility/alignDigit.tsx';
import * as $Utility_normalizeVariableName from './islands/Utility/normalizeVariableName.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
    routes: {
        './routes/_404.tsx': $_404,
        './routes/_app.tsx': $_app,
        './routes/api/help.ts': $api_help,
        './routes/index.tsx': $index,
        './routes/info.tsx': $info,
        './routes/note/bash/post-PlayMinecraftUsingGPU.tsx': $note_bash_post_PlayMinecraftUsingGPU,
        './routes/note/bash/post-SetAutomaticExecutionBashScript.tsx': $note_bash_post_SetAutomaticExecutionBashScript,
        './routes/note/bash/post-Utility.tsx': $note_bash_post_Utility,
        './routes/profile.tsx': $profile,
        './routes/sample.tsx': $sample,
        './routes/template.tsx': $template,
        './routes/terms.tsx': $terms,
    },
    islands: {
        './islands/Common/Code.tsx': $Common_Code,
        './islands/Original/Frame/Board.tsx': $Original_Frame_Board,
        './islands/Original/Frame/Frame.tsx': $Original_Frame_Frame,
        './islands/Original/Frame/FrameFunction.tsx': $Original_Frame_FrameFunction,
        './islands/Original/Frame/FrameObject.tsx': $Original_Frame_FrameObject,
        './islands/Original/Info/Info.tsx': $Original_Info_Info,
        './islands/Original/Info/InfoAdvance.tsx': $Original_Info_InfoAdvance,
        './islands/Original/Menu/Menu.tsx': $Original_Menu_Menu,
        './islands/Original/Miscellaneous/MultilingualContent.tsx': $Original_Miscellaneous_MultilingualContent,
        './islands/Original/Miscellaneous/MultilingualContentSwitcher.tsx': $Original_Miscellaneous_MultilingualContentSwitcher,
        './islands/Utility/Data/getLanguageCodeData.tsx': $Utility_Data_getLanguageCodeData,
        './islands/Utility/Info/getAllInfo.tsx': $Utility_Info_getAllInfo,
        './islands/Utility/Info/getDeviceInfo.tsx': $Utility_Info_getDeviceInfo,
        './islands/Utility/Info/getPlaceInfo.tsx': $Utility_Info_getPlaceInfo,
        './islands/Utility/Info/getTimeInfo.tsx': $Utility_Info_getTimeInfo,
        './islands/Utility/alignDigit.tsx': $Utility_alignDigit,
        './islands/Utility/normalizeVariableName.tsx': $Utility_normalizeVariableName,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
